reload "user.plugins"
reload "user.treesiter"
reload "user.smoothie"
reload "user.fidget"
reload "user.surround"
reload "user.harpoon"
reload "user.colorizer"
reload "user.to-do"
reload "user.spectre"
reload "user.git"
reload "user.inlay-hints"
reload "user.options"
reload "user.functions"
reload "user.keymaps"
reload "user.whichkey"

